# encoding: UTF-8
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[test_fixtures::default]
      - recipe[odsee::install]
      - recipe[odsee::example]
